---
- name: Install Apache on Ubuntu
  hosts: web
  become: yes
  
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: 
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
